### PR TITLE
Add example `apt-get install` lines for build and runtime dependencies

### PR DESCRIPTION
**Pull request by jwal**

### CODE REVIEW

**Comment by jwal** [comment]
It didn't take long to figure these out but it would have been even easier if the `apt-get install` commands were already in the README :)

**Comment by jethrogb** [comment]
Thanks! Can you change "Ubuntu 14.10" to "Debian-based systems"?

**Comment by jwal** [comment]
@jethrogb : How about that?

**Comment by jethrogb** [comment]
Thank you!

**Pull request merged**
